const CommuneWithSpirits = require('./CommuneWithSpirits');
const Exorcism = require('./Exorcism');
const ExpelDemons = require('./ExpelDemons');
const EyesOfTheWolf = require('./EyesOfTheWolf');
const FireGlobe = require('./FireGlobe');
const Forcebonds = require('./Forcebonds');
const GreaterHealing = require('./GreaterHealing');
const Hallucination = require('./Hallucination');
const InvincibleArmor = require('./InvincibleArmor');
const LeyLineTendrilBolts = require('./LeyLineTendrilBolts');
const LeyLineTimeCapsule = require('./LeyLineTimeCapsule');
const Lifeward = require('./Lifeward');
const LightningArc = require('./LightningArc');
const Locate = require('./Locate');
const LuckCurse = require('./LuckCurse');
const MagicalAdrenalRush = require('./MagicalAdrenalRush');
const MetamorphosisHuman = require('./MetamorphosisHuman');
const MinorCurse = require('./MinorCurse');
const NegateMagic = require('./NegateMagic');
const Oracle = require('./Oracle');
const PowerWeapon = require('./PowerWeapon');
const Shockwave = require('./Shockwave');
const Sickness = require('./Sickness');
const SorcerousFury = require('./SorcerousFury');
const SpoilWaterFood = require('./SpoilWaterFood');
const StoneToFlesh = require('./StoneToFlesh');
const WallOfWind = require('./WallOfWind');
const WingedFlight = require('./WingedFlight');
const WispsOfConfusion = require('./WispsOfConfusion');
const WorldBizarre = require('./WorldBizarre');

class InvocationEight{
    constructor(
        communeWithSpirits = new CommuneWithSpirits,
        exorcism = new Exorcism,
        expelDemons = new ExpelDemons,
        eyesOfTheWolf = new EyesOfTheWolf,
        fireGlobe = new FireGlobe,
        forcebonds = new Forcebonds,
        greaterHealing = new GreaterHealing,
        hallucination = new Hallucination,
        invincibleArmor = new InvincibleArmor,
        leyLineTendrilBolts = new LeyLineTendrilBolts,
        leyLineTimeCapsule = new LeyLineTimeCapsule,
        lifeward = new Lifeward,
        lightningArc = new LightningArc,
        locate = new Locate,
        luckCurse = new LuckCurse,
        magicalAdrenalRush = new MagicalAdrenalRush,
        metamorphosisHuman = new MetamorphosisHuman,
        minorCurse = new MinorCurse,
        negateMagic = new NegateMagic,
        oracle = new Oracle,
        powerWeapon = new PowerWeapon,
        shockwave = new Shockwave,
        sickness = new Sickness,
        sorcerousFury = new SorcerousFury,
        spoilWaterFood = new SpoilWaterFood,
        stoneToFlesh = new StoneToFlesh,
        wallOfWind = new WallOfWind,
        wingedFlight = new WingedFlight,
        wispsOfConfusion = new WispsOfConfusion,
        worldBizarre = new WorldBizarre
    ) {
        this.communeWithSpirits = communeWithSpirits;
        this.exorcism = exorcism;
        this.expelDemons = expelDemons;
        this.eyesOfTheWolf = eyesOfTheWolf;
        this.fireGlobe = fireGlobe;
        this.forcebonds = forcebonds;
        this.greaterHealing = greaterHealing;
        this.hallucination = hallucination;
        this.invincibleArmor = invincibleArmor;
        this.leyLineTendrilBolts = leyLineTendrilBolts;
        this.leyLineTimeCapsule = leyLineTimeCapsule;
        this.lifeward = lifeward;
        this.lightningArc = lightningArc;
        this.locate = locate;
        this.luckCurse = luckCurse;
        this.magicalAdrenalRush = magicalAdrenalRush;
        this.metamorphosisHuman = metamorphosisHuman;
        this.minorCurse = minorCurse;
        this.negateMagic = negateMagic;
        this.oracle = oracle;
        this.powerWeapon = powerWeapon;
        this.shockwave = shockwave;
        this.sickness = sickness;
        this.sorcerousFury = sorcerousFury;
        this.spoilWaterFood = spoilWaterFood;
        this.stoneToFlesh = stoneToFlesh;
        this.wallOfWind = wallOfWind;
        this.wingedFlight = wingedFlight;
        this.wispsOfConfusion = wispsOfConfusion;
        this.worldBizarre = worldBizarre;
    }
}

module.exports = InvocationEight;