const Psionic = require('../Psionic');

class MachineGhost extends Psionic {
    constructor() {
        super();
        this.name = 'Machine Ghost';
        this.group = 'Sensitive';
        this.range = 'Self, computer by touch.';
        this.duration = '3 minutes per level of experience.';
        this.cost = '12 I.S.P.';
        this.savingThrow = `Not applicable.`;
        this.description = `    The psychic goes into a trance as he focuses his concentration on entering a computer or most any type of artificial intelligence (not applicable to sentient, self-aware machines like Archie-3). This power is limited to the acquisition or reading of information only. The psychic cannot input, program, or delete data on the machine. He can also access information stored by most electronic means, including computer disks, video and audio disks, film or audio tape, and hard drives. Reading electronically encoded disks and tapes is similar to Object Read, except in this case, he hears and sees the data as if he were playing it on a computer or disk player, only he perceives the information IO times faster. Thus, the character can read (never input) information from disks or broken computers without a physical "jack" connection or an actual display device, i.e. computer and monitor, CD player, etc. 
    As an actual Machine Ghost, the psychic mentally enters and travels the neural network of an active computer. He is actually inside the de-vice. In many ways, this experience is similar to Astral Projection except the psychic is "projecting" into the machine rather than into the Astral Plane. It also has the same pitfalls as Astral Projection, as in the character enters a strange, very seemingly real world that he must learn to navigate. Like Astral Projection, the electronic world of computers takes on a virtual world landscape. This means in the computer virtual world, its programs, viruses and defense mechanisms will take on virtual manifestations that can interact, confront, impede, or attack the Machine Ghost. 
    A password or special access code may appear as a metal door or iron gate, or locked filing cabinet that needs to be (seemingly) broken open to gain access to what is held inside. The more difficult the code, the bigger, stronger and more difficult the door and lock(s). Data is likely to appear as books, paper files, diagrams, film, holograms, and other common means of communication and documentation. The more sophisticated defense measures are likely to appear as one or more guards who must be defeated before the information is accessible. They can appear as sorcerers, Coalition troops, known enemies or exotic aliens. Viruses and defenses designed to attack an intruder typically appear as demons or monsters. 
    Combat in the virtual world seems real and is conducted the same as it would happen in the real world. Combat and damage are measured by the character's perception of his real body armor, weapons and natural powers. When the psychic has lost more than 70% of his armor, or S.D.C./M.D.C., he will feel the urge to flee the virtual world. If he flees, a computer defender will not follow, however a virus will pursue and continue to fight. Although all such damage is only in the mind of the psychic (no physical damage occurs in the real world), if he dies in the virtual world, he can die in the real world as well! The shock to his psyche and body will momentarily stop his heart, and he slumps over dead! The character must roll to save vs coma and death. In this case, physical treatment is not necessary and the recovery process, if successful, takes less than a minute. The psychic must roll three times, and the best two out of three rolls determines life or death. Rolling between 01-75%, two out of three times, means the heart starts and the character is shaken but fine; feels woozy for 204 minutes (reduce Spd 25% and all combat bonuses by half). Failure to recover from the heart attack means immediate CPR medical treatment is required - Paramedic skill will suffice, provided any protective body armor can be removed so that treatment can be given; rescuers have IO minutes. Roll to save vs coma and death again; must roll twice under 80% out of three rolls. 
    The downside in the usage of this power is the psychic loses all sense of time and reality outside the data he is accessing. This means he is oblivious to what is happening around him, and unless protected by a companion, is vulnerable to attack without any means of defense. Pain or being struck or shaken will alert the psychic to trouble, but he has the choice of breaking contact and responding, or ignoring it and continuing to retrieve data. Only Telepathy can reach the character while in this state (can't hear spoken words or sounds outside the computer), and is a means of two-way communication. 
    A character accessing a file on a disk can break contact at any time with a thought. although he will be disoriented for one melee round; re-duce his number of attacks and combat bonuses by half. Breaking free of a computer virtual world is not so easy. 
    Unfortunately, leaving the virtual world of a computer is fundamentally the same as the Astral Plane. The psychic can vaguely sense the way he came and must follow it hack to the virtual access point. To do so. the player must roll on the following table and must roll "definitely certain" to have his character successfully escape. The player must keep trying until he succeeds or time elapses. If the character cannot es-cape virtual space before the duration of this ability elapses, he is flung out with the same effect as "virtual death"; roll to save vs coma and death as described above.`;
        this.note = `The psychic will instinctively know when he's down to the last three minutes of the duration and when trying to exit, can fly toward the way out (typically appears as a door or a dimensional Rift).
    01%-30%: Hopelessly lost (roll again). 
    31%-45%: Uncertain (roll again). 
    46%-65%: Fairly certain on the right track (roll again). 66%-00%: Definitely certain! Whew! Made it back.`;
    }
}

module.exports = MachineGhost;