const Psionic = require('../Psionic');

class AstralProjection extends Psionic {
    constructor() {
        super();
        this.name = 'Astral Projection';
        this.group = 'Sensitive';
        this.range = 'Self.';
        this.duration = '5 minutes per level of experience.';
        this.cost = '8 I.S.P.';
        this.description = `    Through intense concentration/meditation (4D4 minutes of preparation) the psychic can free his mind, or inner self, from his physical body. This psychic inner self is the Astral Body, a whitish, transparent, ghostly image of the character's physical form. A long silver thread or cord connects the Astral Body with its physical self. If the cord is severed the character is likely to die of sudden shock as body and soul are torn asunder. There is only a 30% chance the Astral Self can locate its physical body without the silver umbilical cord (roll best 2 out of 3). 
    The physical body lapses into a coma-like trance when the Astral Self has left it. In this state the body is completely helpless. It cannot walk, move or think; completely catatonic. 
    The hazards are threefold. First, if the physical body is killed, the Astral Body is forever lost and will die, fade away, within six hours. Second, if the Astral Body gets lost or captured while in the Astral Plane. the body will begin to waste away and die. (Note: One minute of our time is equal to one week in the Astral Plane.) Third, the Astral Body is vulnerable to psychic attacks and attacks from ghosts, entities and creatures of the Astral Plane. 
    There are two levels of Astral Projection, coexistence (physical body and spirit form) in the material world and/or the Astral Plane (another dimension). Astral Projection from the physical body into the material world creates a ghostly specter of the Astral Self which can be seen only by other psychics, young children under 13 years old, animals and most supernatural creatures. While in Astral Form the character automatically gains the ability to float, fly (mach one/670 mph/1072 km maximum), see the invisible, pass through solid objects (including M DC walls), impervious to physical harm (including cold, heat and energy). are invisible to sensor systems and cameras, and see and hear as usual. The Astral Body cannot communicate with the physical world except through Telepathy or Empathy, nor speak to, smell or touch anything on the Material Plane. The Astral Self is little more than a mute, ghostly observer. Of course, this is a great way to locate invisible supernatural entities, as well as spy on other humans on the Mate-rial Plane (although limited by short sprints. See duration). A character traveling the Material Plane via Astral Projection may use any psionic powers that do NOT require physical contact. They can generally only affect the physical world (or themselves be affected from physical beings) by Sensitive psionic powers such as Telepathy, Clairvoyance, Empathy, etc.; Astral travelers communicate using Telepathy. 
    Traveling in Astral Form has its own very special dangers. While the character can see the invisible and other Astral Travelers, they can also see him. This makes him susceptible to their psychic and Astral Form attacks, for two Astral Travelers can lock into hand to hand combat as well. The most vulnerable target is the silver cord which is the Astral Traveler's lifeline to the physical world. Fortunately, the cord has an Astral S.D.C. which is two times that of the person's physical Hit Points and S.D.C. combined. The thread-like silver cord is a difficult target to hit; attackers are -6 to strike. The Astral Body also has an S.D.C. of two times the Hit Points and S.D.C. of the physical body combined. This means if the character has 18 Hit Points and 28 S.D.C. both the Astral Body and its silver cord have 92 Astral S.D.C. each (18 + 28 = 46 x 2 = 92 each). Remember, magic and psychic influence have full effect on the Astral Body. This includes exorcism, which will force the Astral Traveler to leave the immediate area (400 foot/122 m radius) and not return for 24 hours. The Astral Traveler has the same number of attacks per melee, bonuses, hand to hand, skills, knowledge and psychic powers that he or she has in the Material Plane.

    Entering the Astral Plane is like entering the Twilight Zone. After a minute of concentration the Astral Gateway appears as a bright patch of shimmering, white light. Once the Astral Traveler passes through it, he will find himself in an endless expanse of white light, and rolling, white clouds. There is no up or down, no bottom or top; no north or south, no land or air or sea, just endless, slowly swirling white. Time, too, is a different or altered state, for what would seem to be a week in the Astral Plane is barely one minute in the physical world. That means a 2nd level Mind Melter could spend the equivalent of ten weeks in the Astral Plane and, when he returned to his physical body, he would find that only ten minutes of real time had elapsed. Although time may flow differently between the Astral Plane and the real world, the Astral Traveler is still subject to the laws of the real world when he returns. If he was low on I.S.P. when he entered the Astral Plane, even if he was there for several weeks of Astral Time, he would still be low on I.S.P. when he returns to the real world. Time and space twisted and distorted, the Astral Traveler can travel from one end of our planet to the other, in the blink of an eye, by hopping through the Astral Plane. However, if he does not know where he is going, he could end up hopelessly lost in the Astral Plane somewhere. Furthermore, the Astral Plane has its dangers as well, from Astral Beings and monsters to be-coming endlessly lost. Even if all goes well, the distortion of place and time makes it extremely difficult to find the material world and one's dormant, physical body. Even trying to follow the silver cord can lead to nowhere.

    To return from the Astral Plane to the physical body, roll on the following table: Each roll will determine the Astral Traveler's state of mind and sense of direction. The percentile dice can be rolled up to three times per melee (15 seconds). The player must roll "definitely certain" to successfully return. The player may keep trying until he succeeds or time elapses. 

Location of the Physical Body 
Roll Percentile Dice to Return from the Astral Plane:
01%-30%: Hopelessly Lost (roll again). 
31%-50%: Uncertain, Confused (roll again). 
51%-76%: Fairly certain of location; on the right track (roll again). 
77%-00%: Definitely certain of location. (Whew! Made it Back).

    Astral travel with a partner is a much safer way to travel, because if one can find his body, he can lead the other one out with him.`;
        this.note = `Traveling on the Material Plane in Astral Form is infinitely easier than the Astral Plane. To find the physical body the character need only return to where he left it. If it has been moved or hidden the Astral Self can sense its location with a 60% efficiency (roll once per melee). 
    The other danger lies in being attacked by other beings in the Astral Plane. Entities and elemental creatures of magic live in the Astral Plane or travel through it. These beings are usually hostile, evil forces. While the Astral Body cannot touch or communicate with the material world, the Astral Body is quite solid to other inhabitants of the Astral Plane. The Astral Body is also vulnerable to magic and psychic powers, as well as physical assault by Astral Entities. 
    The energy which composes the Astral Plane is responsive to thoughts and desires. The strongest Astral Beings can mentally or magically control what a small area might look like. This means that the Astral Plane is made up of hundreds or perhaps thousands or even millions of tiny Astral "Kingdoms" adrift within the vast whiteness. Exactly what these kingdoms look like is up to the entity that creates it. Some may look like a modern city, others like castles or forests, while still others, a frightening landscape. Perhaps this is where legends of visitations to Heaven and Hell originate? It is always wise to avoid an Astral Kingdom, because only the most powerful Entities and Astral Beings can create and maintain them.
`;
    }
}

module.exports = AstralProjection;