const BioManipulation = require('./BioManipulation');
const BioRegenerationSuper = require('./BioRegenerationSuper');
const Electrokinesis = require('./Electrokinesis');
const EmpathicTransmission = require('./EmpathicTransmission');
const GroupMindBlock = require('./GroupMindBlock');
const GroupTrance = require('./GroupTrance');
const Hydrokinesis = require('./Hydrokinesis');
const HypnoticSuggestion = require('./HypnoticSuggestion');
const MentallyPossessOthers = require('./MentallyPossessOthers');
const MindBlockAutoDefense = require('./MindBlockAutoDefense');
const MindBolt = require('./MindBolt');
const MindBond = require('./MindBond');
const MindWipe = require('./MindWipe');
const PPEShield = require('./PPEShield');
const PsiShield = require('./PsiShield');
const PsiSword = require('./PsiSword');
const PsionicInvisibility = require('./PsionicInvisibility');
const PsychicBodyField = require('./PsychicBodyField');
const PsychicOmniSight = require('./PsychicOmniSight');
const PsychosomaticDisease = require('./PsychosomaticDisease');
const Pyrokinesis = require('./Pyrokinesis');
const RadiateHorrorFactor = require('./RadiateHorrorFactor');
const TelekinesisSuper = require('./TelekinesisSuper');
const TelekineticAccelerationAttack = require('./TelekineticAccelerationAttack');
const TelekineticForceField = require('./TelekineticForceField');
const Telemechanics = require('./Telemechanics');
const TelemechanicMentalOperation = require('./TelemechanicMentalOperation');
const TelemechanicParalysis = require('./TelemechanicParalysis');
const TelemechanicPossession = require('./TelemechanicPossession');

class SuperPsionics {
    constructor(
        bioManipulation = new BioManipulation,
        bioRegenerationSuper = new BioRegenerationSuper,
        electrokinesis = new Electrokinesis,
        empathicTransmission = new EmpathicTransmission,
        groupMindBlock = new GroupMindBlock,
        groupTrance = new GroupTrance,
        hydrokinesis = new Hydrokinesis,
        hypnoticSuggestion = new HypnoticSuggestion,
        mentallyPossessOthers = new MentallyPossessOthers,
        mindBlockAutoDefense = new MindBlockAutoDefense,
        mindBolt = new MindBolt,
        mindBond = new MindBond,
        mindWipe = new MindWipe,
        pPEShield = new PPEShield,
        psiShield = new PsiShield,
        psiSword = new PsiSword,
        psionicInvisibility = new PsionicInvisibility,
        psychicBodyField = new PsychicBodyField,
        psychicOmniSight = new PsychicOmniSight,
        psychosomaticDisease = new PsychosomaticDisease,
        pyrokinesis = new Pyrokinesis,
        radiateHorrorFactor = new RadiateHorrorFactor,
        telekinesisSuper = new TelekinesisSuper,
        telekineticAccelerationAttack = new TelekineticAccelerationAttack,
        telekineticForceField = new TelekineticForceField,
        telemechanics = new Telemechanics,
        telemechanicMentalOperation = new TelemechanicMentalOperation,
        telemechanicParalysis = new TelemechanicParalysis,
        telemechanicPossession = new TelemechanicPossession
    ) {
        this.bioManipulation = bioManipulation;
        this.bioRegenerationSuper = bioRegenerationSuper;
        this.electrokinesis = electrokinesis;
        this.empathicTransmission = empathicTransmission;
        this.groupMindBlock = groupMindBlock;
        this.groupTrance = groupTrance;
        this.hydrokinesis = hydrokinesis;
        this.hypnoticSuggestion = hypnoticSuggestion;
        this.mentallyPossessOthers = mentallyPossessOthers;
        this.mindBlockAutoDefense = mindBlockAutoDefense;
        this.mindBolt = mindBolt;
        this.mindBond = mindBond;
        this.mindWipe = mindWipe;
        this.pPEShield = pPEShield;
        this.psiShield = psiShield;
        this.psiSword = psiSword;
        this.psionicInvisibility = psionicInvisibility;
        this.psychicBodyField = psychicBodyField;
        this.psychicOmniSight = psychicOmniSight;
        this.psychosomaticDisease = psychosomaticDisease;
        this.pyrokinesis = pyrokinesis;
        this.radiateHorrorFactor = radiateHorrorFactor;
        this.telekinesisSuper = telekinesisSuper;
        this.telekineticAccelerationAttack = telekineticAccelerationAttack;
        this.telekineticForceField = telekineticForceField;
        this.telemechanics = telemechanics;
        this.telemechanicMentalOperation = telemechanicMentalOperation;
        this.telemechanicParalysis = telemechanicParalysis;
        this.telemechanicPossession = telemechanicPossession;
    }
}

module.exports = SuperPsionics;