const Airplane = require('./Airplane');
const Automobile = require('./Automobile');
const Bicycling = require('./Bicycling');
const BoatsMotorAndHydrofoils = require('./BoatsMotorAndHydrofoils');
const BoatsPaddleTypes = require('./BoatsPaddleTypes');
const BoatsSailTypes = require('./BoatsSailTypes');
const BoatsShips = require('./BoatsShips');
const CombatDriving = require('./CombatDriving');
const FlightSystemCombat = require('./FlightSystemCombat');
const Helicopter = require('./Helicopter');
const HoverCraftGround = require('./HoverCraftGround');
const HovercyclesOrSkycyclesOrRocketBikes = require('./HovercyclesOrSkycyclesOrRocketBikes');
const JetAircraft = require('./JetAircraft');
const JetPacks = require('./JetPacks');
const JumpBikeCombat = require('./JumpBikeCombat');
const MilitaryCombatHelicopter = require('./MilitaryCombatHelicopter');
const MilitaryJetFighter = require('./MilitaryJetFighter');
const MilitarySubmersibles = require('./MilitarySubmersibles');
const MilitaryTanksAndApcs = require('./MilitaryTanksAndApcs');
const MilitaryWarshipsAndPatrolBoats = require('./MilitaryWarshipsAndPatrolBoats');
const MotorcyclesAndSnowmobiles = require('./MotorcyclesAndSnowmobiles');
const RobotsAndPowerArmor = require('./RobotsAndPowerArmor');
const RobotCombatBasic = require('./RobotCombatBasic');
const RobotCombatElite = require('./RobotCombatElite');
const TrackedAndConstructionVehicles = require('./TrackedAndConstructionVehicles');
const Truck = require('./Truck');
const WaterScooters = require('./WaterScooters');
const WaterSkiingAndSurfing = require('./WaterSkiingAndSurfing');

class Pilot {
    constructor(
        airplane = new Airplane,
        automobile = new Automobile,
        bicycling = new Bicycling,
        boatsMotorAndHydrofoils = new BoatsMotorAndHydrofoils,
        boatsPaddleTypes = new BoatsPaddleTypes,
        boatsSailTypes = new BoatsSailTypes,
        boatsShips = new BoatsShips,
        combatDriving = new CombatDriving,
        flightSystemCombat = new FlightSystemCombat,
        helicopter = new Helicopter,
        hoverCraftGround = new HoverCraftGround,
        hovercyclesOrSkycyclesOrRocketBikes = new HovercyclesOrSkycyclesOrRocketBikes,
        jetAircraft = new JetAircraft,
        jetPacks = new JetPacks,
        jumpBikeCombat = new JumpBikeCombat,
        militaryCombatHelicopter = new MilitaryCombatHelicopter,
        militaryJetFighter = new MilitaryJetFighter,
        militarySubmersibles = new MilitarySubmersibles,
        militaryTanksAndApcs = new MilitaryTanksAndApcs,
        militaryWarshipsAndPatrolBoats = new MilitaryWarshipsAndPatrolBoats,
        motorcyclesAndSnowmobiles = new MotorcyclesAndSnowmobiles,
        robotsAndPowerArmor = new RobotsAndPowerArmor,
        robotCombatBasic = new RobotCombatBasic,
        robotCombatElite = new RobotCombatElite,
        trackedAndConstructionVehicles = new TrackedAndConstructionVehicles,
        truck = new Truck,
        waterScooters = new WaterScooters,
        waterSkiingAndSurfing = new WaterSkiingAndSurfing
    ) {
        this.airplane = airplane;
        this.automobile = automobile;
        this.bicycling = bicycling;
        this.boatsMotorAndHydrofoils = boatsMotorAndHydrofoils;
        this.boatsPaddleTypes = boatsPaddleTypes;
        this.boatsSailTypes = boatsSailTypes;
        this.boatsShips = boatsShips;
        this.combatDriving = combatDriving;
        this.flightSystemCombat = flightSystemCombat;
        this.helicopter = helicopter;
        this.hoverCraftGround = hoverCraftGround;
        this.hovercyclesOrSkycyclesOrRocketBikes = hovercyclesOrSkycyclesOrRocketBikes;
        this.jetAircraft = jetAircraft;
        this.jetPacks = jetPacks;
        this.jumpBikeCombat = jumpBikeCombat;
        this.militaryCombatHelicopter = militaryCombatHelicopter;
        this.militaryJetFighter = militaryJetFighter;
        this.militarySubmersibles = militarySubmersibles;
        this.militaryTanksAndApcs = militaryTanksAndApcs;
        this.militaryWarshipsAndPatrolBoats = militaryWarshipsAndPatrolBoats;
        this.motorcyclesAndSnowmobiles = motorcyclesAndSnowmobiles;
        this.robotsAndPowerArmor = robotsAndPowerArmor;
        this.robotCombatBasic = robotCombatBasic;
        this.robotCombatElite = robotCombatElite;
        this.trackedAndConstructionVehicles = trackedAndConstructionVehicles;
        this.truck = truck;
        this.waterScooters = waterScooters;
        this.waterSkiingAndSurfing = waterSkiingAndSurfing;
    }
}

module.exports = Pilot;