const AppraiseGoods = require('./AppraiseGoods');
const Art = require('./Art');
const Begging = require('./Begging');
const BreedDogs = require('./BreedDogs');
const Calligraphy = require('./Calligraphy');
const ComputerOperation = require('./ComputerOperation');
const ComputerProgramming = require('./ComputerProgramming');
const CyberneticsBasic = require('./CyberneticsBasic');
const Excavation = require('./Excavation');
const Firefighting = require('./Firefighting');
const Gemology = require('./Gemology');
const GeneralRepairAndMaintenance = require('./GeneralRepairAndMaintenance');
const HistoryPostApocalypse = require('./HistoryPostApocalypse');
const HistoryPreRifts = require('./HistoryPreRifts');
const JuryRig = require('./JuryRig');
const LawGeneral = require('./LawGeneral');
const LeatherWorking = require('./LeatherWorking');
const LoreAmericanIndiansTechnical = require('./LoreAmericanIndiansTechnical');
const LoreCattleAndAnimals = require('./LoreCattleAndAnimals');
const LoreDBee = require('./LoreDBee');
const LoreDemonsAndMonsters = require('./LoreDemonsAndMonsters');
const LoreFaerieAndCreaturesOfMagic = require('./LoreFaerieAndCreaturesOfMagic');
const LoreJuicers = require('./LoreJuicers');
const LoreMagic = require('./LoreMagic');
const LorePsychicsAndPsionics = require('./LorePsychicsAndPsionics');
const Masonry = require('./Masonry');
const Mining = require('./Mining');
const Mythology = require('./Mythology');
const Philosophy = require('./Philosophy');
const Photography = require('./Photography');
const Prospecting = require('./Prospecting');
const RecycleTechnical = require('./RecycleTechnical');
const Research = require('./Research');
const RopeWorks = require('./RopeWorks');
const Salvage = require('./Salvage');
const Ventriloquism = require('./Ventriloquism');
const WhittlingAndSculpting = require('./WhittlingAndSculpting');

class Technical {
    constructor(
        appraiseGoods = new AppraiseGoods,
        art = new Art,
        begging = new Begging,
        breedDogs = new BreedDogs,
        calligraphy = new Calligraphy,
        computerOperation = new ComputerOperation,
        computerProgramming = new ComputerProgramming,
        cyberneticsBasic = new CyberneticsBasic,
        excavation = new Excavation,
        firefighting = new Firefighting,
        gemology = new Gemology,
        generalRepairAndMaintenance = new GeneralRepairAndMaintenance,
        historyPostApocalypse = new HistoryPostApocalypse,
        historyPreRifts = new HistoryPreRifts,
        juryRig = new JuryRig,
        lawGeneral = new LawGeneral,
        leatherWorking = new LeatherWorking,
        loreAmericanIndiansTechnical = new LoreAmericanIndiansTechnical,
        loreCattleAndAnimals = new LoreCattleAndAnimals,
        loreDBee = new LoreDBee,
        loreDemonsAndMonsters = new LoreDemonsAndMonsters,
        loreFaerieAndCreaturesOfMagic = new LoreFaerieAndCreaturesOfMagic,
        loreJuicers = new LoreJuicers,
        loreMagic = new LoreMagic,
        lorePsychicsAndPsionics = new LorePsychicsAndPsionics,
        masonry = new Masonry,
        mining = new Mining,
        mythology = new Mythology,
        philosophy = new Philosophy,
        photography = new Photography,
        prospecting = new Prospecting,
        recycleTechnical = new RecycleTechnical,
        research = new Research,
        ropeWorks = new RopeWorks,
        salvage = new Salvage,
        ventriloquism = new Ventriloquism,
        whittlingAndSculpting = new WhittlingAndSculpting
    ) {
        this.appraiseGoods = appraiseGoods;
        this.art = art;
        this.begging = begging;
        this.breedDogs = breedDogs;
        this.calligraphy = calligraphy;
        this.computerOperation = computerOperation;
        this.computerProgramming = computerProgramming;
        this.cyberneticsBasic = cyberneticsBasic;
        this.excavation = excavation;
        this.firefighting = firefighting;
        this.gemology = gemology;
        this.generalRepairAndMaintenance = generalRepairAndMaintenance;
        this.historyPostApocalypse = historyPostApocalypse;
        this.historyPreRifts = historyPreRifts;
        this.juryRig = juryRig;
        this.lawGeneral = lawGeneral;
        this.leatherWorking = leatherWorking;
        this.loreAmericanIndiansTechnical = loreAmericanIndiansTechnical;
        this.loreCattleAndAnimals = loreCattleAndAnimals;
        this.loreDBee = loreDBee;
        this.loreDemonsAndMonsters = loreDemonsAndMonsters;
        this.loreFaerieAndCreaturesOfMagic = loreFaerieAndCreaturesOfMagic;
        this.loreJuicers = loreJuicers;
        this.loreMagic = loreMagic;
        this.lorePsychicsAndPsionics = lorePsychicsAndPsionics;
        this.masonry = masonry;
        this.mining = mining;
        this.mythology = mythology;
        this.philosophy = philosophy;
        this.photography = photography;
        this.prospecting = prospecting;
        this.recycleTechnical = recycleTechnical;
        this.research = research;
        this.ropeWorks = ropeWorks;
        this.salvage = salvage;
        this.ventriloquism = ventriloquism;
        this.whittlingAndSculpting = whittlingAndSculpting;
    }
}

module.exports = Technical;